// One continuous Smoke and Glass excerpt, followed by a quiet release to the page.
// The complete retimed live performance starts at show 60.1742; assets/v2/sync.json owns its map.
const media = '/theatre/assets/v2/';
export const soundtrack = media + 'soundtrack.mp3?v=20261009i';
export const chapters = [
  { id: 'arrival', group: 'A few things', seconds: 4.0245, anchor: '.hero', kind: 'opening', theme: 'paper',
    title: 'A few things\nI like making.', href: '#about', link: 'Jack Ormondroyd',
    image: media + 'photo-mic.webp', alt: 'Jack singing and playing guitar live in warm stage light.',
    secondImage: media + 'photo-blue-profile.webp', caption: 'Music / movement / things that work' },
  { id: 'skating', group: 'Outside', seconds: 9.6, anchor: '#about', kind: 'skate-film', theme: 'paper',
    title: 'A different\nkind of practice.', href: 'https://www.instagram.com/raskyskate/', link: '@raskyskate',
    image: media + 'skate-montage-poster.jpg?v=20261009i', video: media + 'skate-montage.mp4?v=20261009i', mobileImage: media + 'skate-montage-mobile-poster.jpg?v=20261009i', mobileVideo: media + 'skate-montage-mobile.mp4?v=20261009i',
    graphics: [{ src: '/assets/design/skate/rasky-padlock.png', alt: 'RASKY skate graphic: a skeleton jumping with a padlock.' }, { src: '/assets/design/skate/rasky-road.png', alt: 'RASKY skate graphic: a skeleton skating along a road.' }],
    alt: 'Three skate tricks in motion: short setups, full tricks and landings, finishing with the kickflip over the cone.', caption: 'Three tricks. Same urge. / @raskyskate', cues: [0, 3.7, 6.1] },
  { id: 'skate-photo', group: 'Outside', seconds: 5.15, anchor: '#about', kind: 'skate-photo', theme: 'paper',
    title: 'One frame.\nA lot going on.', href: 'https://www.instagram.com/raskyskate/', link: 'Outside, with a board',
    image: media + 'treflip.jpg', alt: 'Jack’s quarter-pipe tre-flip photograph, with the skateboard suspended mid-spin.',
    graphics: [{ src: '/assets/design/skate/rasky-heart.png', alt: 'RASKY skate graphic: a broken heart made from skateboard decks.' }, { src: '/assets/design/skate/rasky-arch.png', alt: 'RASKY skate graphic: a skeleton emerging from a brick arch.' }],
    caption: 'On the board. On paper, too. / Skate graphics by me', cues: [0, 2.4] },
  { id: 'bar-tools', group: 'Built for a shift', seconds: 5.4, anchor: '#bar-tools-title', kind: 'bar-tools', theme: 'paper',
    title: 'Made for\na busy shift.', href: '/bar-tools/', link: 'The bar app',
    screens: [{ src: media + 'bar-recipe.webp', alt: 'Genuine Sea Glass sample recipe with its image and per-serve ingredients.', label: 'The recipe.' }, { src: media + 'bar-batch.webp', alt: 'The Sea Glass sample recipe scaled to 25 serves, with ingredient totals and wastage.', label: '25 serves.' }, { src: media + 'bar-prep.webp', alt: 'Genuine prep quantities and progress.', label: 'Prep, planned.' }],
    alt: 'Real iPhone Simulator screens of Jack’s bar app: batch calculation and preparation tools.',
    caption: 'Bar / service tools · iOS app · Simulator screens', words: ['The recipe.', '25 serves.', 'Prep, planned.'], cues: [0, 1.8, 3.6] },
  { id: 'raskys', group: 'A place of my own', seconds: 7.9413, anchor: '#raskys-title', kind: 'vision', theme: 'dark',
    title: 'Raskys.\nA place of my own.', text: 'Years in hospitality. A plan for something bigger.', href: '/raskys/', link: 'Explore the vision',
    image: '/assets/optimized/raskys-hero-venue.webp', alt: 'The existing Raskys venue concept from the main website: warm windows, live music and the red Raskys sign.',
    caption: 'Raskys · venue vision & business plan · concept visualisation', cues: [0, 3.4] },
  { id: 'detail', group: 'Things that work', seconds: 9.5, anchor: '#perfecthost-title', kind: 'interaction', theme: 'paper',
    title: 'A little less\nto keep in your head.', href: '/perfecthost-demo/', link: 'Try the prototype',
    image: media + 'perfecthost-combined-poster.jpg?v=20261009i', manualImage: media + 'perfecthost-combined-end.jpg?v=20261009i', video: media + 'perfecthost-combined.mp4?v=20261009i',
    alt: 'Table 12: changing the guest count, marking service steps and saving a sample note in the real prototype.',
    caption: 'Perfect Host · interactive prototype · sample table', words: ['Pick a table.', 'Four guests.', 'Service noted.', 'Note saved.'], cues: [0, 2.6, 4.25, 8.4] },
  { id: 'etsycalc', group: 'Things that work', seconds: 7.4248, anchor: '.project-row[href="/etsycalc/"]', kind: 'calculator', theme: 'violet',
    title: 'Make it\nmake sense.', href: '/etsycalc/', link: 'Open EtsyCalc',
    image: media + 'etsycalc-workflow-poster.jpg?v=20261009i', video: media + 'etsycalc-workflow.mp4?v=20261009i', mobileVideo: media + 'etsycalc-mobile.mp4?v=20261009i', mobileImage: media + 'etsycalc-mobile-poster.jpg?v=20261009i',
    alt: 'EtsyCalc recalculating estimated profit as actual price and cost inputs change.', caption: 'EtsyCalc · working estimator · sample inputs' },
  { id: 'practice', group: 'Smoke & Glass', seconds: 11.1336, anchor: '#music', kind: 'practice', theme: 'dark',
    title: 'Smoke\n& Glass.', text: 'Working things out.', href: '/music/', link: 'Raskyjack',
    image: media + 'practice-guitar-poster.jpg?v=20261009i', video: media + 'practice-guitar.mp4?v=20261009i',
    alt: 'Jack playing electric guitar at home. Process footage, with the Smoke and Glass remix soundtrack.',
    caption: 'At home / Smoke & Glass · practice + remix', cues: [0, 3.9, 7.8] },
  { id: 'music', group: 'Smoke & Glass', seconds: 32.4506, anchor: '#music', kind: 'performance', theme: 'dark',
    title: 'Then,\nout loud.', href: '/music/', link: 'More music', caption: 'Smoke & Glass / live guitar × original remix',
    image: media + 'guitar-poster.jpg', video: media + 'guitar-synced.mp4?v=20261009i', alt: 'Jack’s whole live guitar solo with its actual recording and aligned remix accompaniment.',
    ambientVideos: [{ src: media + 'guitar-portrait-blue.mp4', poster: media + 'guitar-portrait-blue-poster.jpg', alt: 'Full portrait of Jack playing guitar in blue light, from another moment in the original band footage.', start: 5.19, end: 10.3913 }, { src: media + 'guitar-portrait-warm.mp4', poster: media + 'guitar-portrait-warm-poster.jpg', alt: 'Jack’s face and guitar in warm stage light, from another moment in the original band footage.', start: 10.3913, end: 20.7706 }, { src: media + 'guitar-portrait-violet.mp4', poster: media + 'guitar-portrait-violet-poster.jpg', alt: 'A complete portrait frame of Jack performing in violet light, from another moment in the original band footage.', start: 20.7706, end: 28.5028 }],
    secondImage: media + 'photo-green-stage.webp', thirdImage: media + 'photo-guitar-hands.webp', cues: [0, 5.19, 10.3913, 20.7706, 28.5028] },
  { id: 'raskode', group: 'Making the tools', seconds: 4.6, anchor: '.project-row[href="/raskode/"]', kind: 'code', theme: 'dark',
    title: 'Tools for\nmaking things.', text: 'Raskode. My own AI tooling.', href: '/raskode/', link: 'About Raskode',
    caption: 'Raskode · personal development tooling · in progress', cues: [0, .6, 1.5, 2.5] },
  { id: 'sports', group: 'Sport meets data', seconds: 5.8, anchor: '.project-row[href="/sportspredict/"]', kind: 'dashboard', theme: 'dark',
    title: 'Sport.\nWith more context.', words: ['Match predictions.', 'The bigger picture.'], cues: [0, 3],
    href: '/sportspredict/', link: 'SportsPredict',
    screens: [{ src: media + 'sports-predictions-concept.webp', alt: 'Complete Predictions design from the SportsPredictions repository, with example match probabilities.', label: 'Match predictions.' }, { src: media + 'sports-overview-concept.webp', alt: 'Complete Overview design from the SportsPredictions repository, with illustrative charts and sample figures.', label: 'The bigger picture.' }],
    caption: 'SportsPredict · repository interface concepts · sample figures' },
  { id: 'novel', group: 'An idea grows', seconds: 3.2, anchor: '#side-title', kind: 'novel', theme: 'paper',
    title: 'First,\na novel.', href: '/shnork/', link: 'In the Shadow of a Shnork',
    image: media + 'shnork-novel-poster.jpg', manualImage: media + 'shnork-novel-end.jpg?v=20261009i', video: media + 'shnork-novel-scroll.mp4?v=20261009i', alt: 'An accelerating scroll through all 42 pages of the actual novel preview, ending on its last illustrated page.', caption: 'In the Shadow of a Shnork · pages from the novel' },
  { id: 'shnork', group: 'A world of its own', seconds: 6.9951, anchor: '#side-title', kind: 'game', theme: 'dark',
    title: 'Then, a world\nto walk around in.', text: 'In the Shadow of a Shnork.', href: '/shnorkgame/', link: 'Enter Shnorkscape',
    image: media + 'shnork-environment-poster.jpg', video: media + 'shnork-environment.mp4',
    mobileImage: media + 'shnork-environment-mobile-poster.jpg', mobileVideo: media + 'shnork-environment-mobile.mp4',
    alt: 'Actual Shnorkscape environment footage: the river glade and an upstream forest view, with water, foliage and warm light.', caption: 'Shnorkscape · game in development' },
  { id: 'finish', group: 'Over to you', seconds: 3.5, anchor: '.hero', kind: 'finish', theme: 'paper',
    title: 'Anyway.\nThat’s me.', text: 'Have a look around.' }
];
export const duration = chapters.reduce((total, chapter) => total + chapter.seconds, 0);
