/* Defence-first interface. Deterministic prompts; local case data; no remote processing. */
(() => {
'use strict';
const KEY='rwdef.case.v1', MODE='rwdef.share', $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID(), now=()=>new Date().toISOString(), stamp=t=>new Date(t).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'});
const docs=window.RW_DOCUMENTS, quotes=window.RW_QUOTES, laws=window.RW_LEGAL, bank=window.RW_DEFENCE;
const checks=[['consumption','Drinking'],['working','Working time / responsibility'],['lockup','Lock-up duty'],['service','Active service finished'],['intox','Intoxication'],['risk','Specific serious performance / safety risk']];
const statuses=['Not established','I accept this','Supported by evidence','I dispute this'];
let state={version:1,created:now(),notes:'',log:[],questions:[],audit:[],attachments:[],facts:{},evidence:[],mitigation:{},outcome:{},appeal:{}},saved=true,loadError='';
try{const raw=localStorage.getItem(KEY);if(raw){const x=validate(JSON.parse(raw));if(x.version!==1)throw Error('Unknown backup version');state={...state,...x};}}catch(e){loadError='Saved data could not be loaded. Export your existing storage before replacing it.';saved=false;}
function defaults(){state.defence??={};const d=state.defence;d.checks??={};checks.forEach(([k])=>{d.checks[k]??={status:'Not established',source:''};});d.accept??='';d.dispute??='';d.explain??='';d.mitigate??='';d.mitigationRaised??=false;d.incident??=false;d.incidentDetail??='';d.promise??=false;d.errorAccepted??=false;d.sanction??='Not given';d.appealGrounds??={};state.log??=[];state.questions??=[];state.attachments??=[];}
defaults();let route='defend',query='',selected='',searchOpen=false,show=false,sourceIds=[],sourceQuery='',lastFocus=null,overlayType='',pendingImport=null,sourceOrigin='';
try{show=sessionStorage.getItem(MODE)==='true';}catch{}
function get(path){return path.split('.').reduce((o,k)=>o?.[k],state);}
function put(path,value){const ks=path.split('.');if(ks.some(k=>['__proto__','constructor','prototype'].includes(k)))return;let o=state;ks.slice(0,-1).forEach(k=>{o[k]??={};o=o[k];});o[ks.at(-1)]=value;}
function save(){if(loadError){notice(loadError);return;}state.updated=now();try{localStorage.setItem(KEY,JSON.stringify(state));saved=true;}catch{saved=false;notice('Not saved. Browser storage is unavailable or full. Export a backup.');}const e=$('#save-state');if(e)e.textContent=saved?'Saved on this device':'Not saved · export';}
function log(type,text){state.log.push({id:uid(),created:now(),type,note:text,status:'EMPLOYEE RECORD'});save();}
const d=()=>state.defence;
const established=k=>d().incident&&(d().checks[k].status==='I accept this'||(d().checks[k].status==='Supported by evidence'&&d().checks[k].source.trim()));
function defence(){let level=1;if(established('consumption'))level=2;if(established('consumption')&&established('working'))level=3;if(level===3&&established('risk')&&d().checks.risk.source.trim())level=4;if(d().sanction==='Dismissal')level=5;
const levels=[null,
{title:'Establish the incident first.',best:'Do not defend an assumed incident. Get the exact allegation and evidence.',say:'Please identify the exact incident, time and evidence before I respond.',risk:'Guessing the incident could create an unnecessary admission.',handle:'Answer the allegation actually put to you. Be accurate; do not volunteer unrelated incidents.',source:'acas-notice'},
{title:established('consumption')?'Keep the focus on working status.':'Establish what the evidence proves.',best:established('consumption')?'Do not fight established consumption. Clarify working status, then classification.':'The incident is identified. Separate what you accept from what remains disputed.',say:established('consumption')?'I accept the consumption established. Please clarify the working status and duties you rely upon.':'I will answer the specific allegation and distinguish what I accept from what remains disputed.',risk:established('lockup')?'Your lock-up duty may support the argument that you were still working.':'Clocking, supervision and lock-up can show that work responsibilities remained.',handle:'Do not equate the end of service with the end of all duties. Accept an established responsibility.',source:'security'},
{title:'Separate breach, gross misconduct and dismissal.',best:'Accept the established rule breach. Challenge the gross-misconduct classification and ask for a proportionate sanction.',say:'I accept I should have waited before drinking during working time. I ask you to assess gross misconduct and sanction separately.',risk:'The alcohol wording says “could affect”; actual harm is not required.',handle:'Ask for the specific potential effect in the actual circumstances. Do not rely only on “nothing happened”.',source:'alcohol-gross-disciplinary'},
{title:'Move the emphasis to keeping your employment.',best:'Serious risk evidence weakens a classification challenge. Address it honestly and emphasise supported mitigation and a lesser sanction.',say:'I recognise the seriousness of the established risk. Please consider the mitigation I can support and whether a lesser sanction would address the concern.',risk:'Denying strong risk evidence could damage your credibility.',handle:'Accept what is established. Explain what would change; do not claim an isolated error or promise no repetition unless true.',source:'sanctions'},
{title:'Preserve your position. Prepare the appeal.',best:'Get the findings and reasons in writing, preserve your record and act on the appeal deadline.',say:'Please provide the findings, reasons, effective date and appeal instructions in writing. I am not resigning.',risk:'The handbook gives five working days from the decision for a written appeal.',handle:'Record the decision date and confirm the deadline. Do not wait for an internal appeal to check any external time limits.',source:'appeal'}];if(level===3&&established('intox'))levels[3]={...levels[3],risk:'Accepted intoxication alongside continuing duties strengthens the employer’s gross-misconduct case.',handle:'Do not deny intoxication you have accepted. Address the actual duties and potential effect, then emphasise supported mitigation and a lesser sanction.'};if(level===1&&d().incident)levels[1]={...levels[1],title:'Establish what the evidence proves.',best:'The incident is identified. Establish consumption and the disputed facts before addressing classification.',say:'Please show the evidence for the conduct alleged so I can distinguish what I accept from what I dispute.',risk:'Do not deny consumption that reliable evidence clearly establishes.',handle:'Review the actual material before responding. Accept the facts it proves and address working status and seriousness separately.',source:'acas-hearing'};return {level,...levels[level]};}
function response(id){const original=bank.find(r=>r.id===id)||bank.find(r=>r.id==='other');const r={...original};const f=defence();
if(id==='working'&&established('consumption'))r.say=established('working')?'I accept I should have waited while work responsibilities remained. I still ask that the gross-misconduct classification is considered separately.':'If that period was working time, I accept I should have waited. I still dispute that this automatically makes the circumstances gross misconduct.';
if(id==='working'&&established('consumption')&&established('service')&&established('lockup')&&!established('working'))r.say='Active service had finished, although I retained responsibility for securing the premises. If that was working time, I accept I should have waited; gross misconduct and sanction still need separate consideration.';
if(id==='lockup'&&established('lockup'))r.say=established('consumption')?'I accept I retained responsibility for securing the premises and should have waited if that was still working time. I ask that gross misconduct is considered separately from that mistake.':'I accept the lock-up responsibility established. Please explain how the alleged conduct created the specific risk relied upon for gross misconduct.';
if(id==='lockup'&&established('lockup')&&established('service')&&established('consumption'))r.say='I accept the lock-up duty remained after active service finished. If that was still working time, I should have waited; I ask that gross misconduct is considered separately from that mistake.';
if(['intox','witnessdrunk'].includes(id)){if(d().incident&&d().checks.intox.status==='I dispute this')r.say='I dispute that I was intoxicated. Please identify the observations supporting that allegation.';else if(established('intox'))r.say='I will not deny the intoxication established. I ask you to consider the circumstances, my supported mitigation and whether a lesser sanction is sufficient.';}
if(['manager','better'].includes(id)&&f.level>=3)r.say='I accept the responsibility of my role and the judgement I should have exercised. I ask that the actual circumstances and mitigation determine the classification and sanction.';
if(id==='accept'&&f.level>=3)r.say='I accept that drinking during the working time established breached the alcohol rule. I ask that gross misconduct and sanction be considered separately.';
if(['accept-gross','gross','any'].includes(id)&&f.level>=4&&f.level<5)r.say='I recognise that the evidence supports a serious concern and will not minimise it. I ask you to consider the complete circumstances, mitigation and whether a lesser sanction is sufficient.';
if(id==='sorry'&&d().errorAccepted)r.say=d().promise?'Yes, I am sorry for the mistake I have acknowledged, and I would not repeat it. I still ask that the circumstances and mitigation inform the sanction.':'Yes, I am sorry for the mistake I have acknowledged. I ask that my explanation and mitigation are considered.';
if(['keep','dismiss'].includes(id)&&d().errorAccepted&&d().promise)r.say='I have acknowledged the judgement I would change and I would not repeat it. I ask you to consider my supported mitigation and whether a warning is sufficient rather than ending my employment.';
if(id==='cctv'&&established('consumption'))r.say='I do not dispute the consumption the footage clearly establishes. Please consider its full context when assessing classification and sanction.';
if(id==='close')r.say=closing();return r;}
function closing(){const f=defence();let text=f.level===1?'Please identify the precise allegation and evidence so I can respond accurately.':f.level>=4?'I recognise the seriousness of the evidence established and ask that it is considered alongside my explanation.':f.level===3?'I accept I should have waited before drinking during working time; I ask that gross misconduct and sanction are considered separately.':'Please distinguish the facts I accept from those still disputed and assess the complete circumstances.';if(d().promise)text+=' I would not repeat the conduct I have acknowledged.';if(d().mitigate.trim()&&d().mitigationRaised)text+=' Please weigh the mitigation I have raised.';text+=' Please consider whether a lesser sanction is sufficient.';return text;}
const btn=(text,action,data='',cls='')=>`<button class="btn ${cls}" data-action="${action}" ${data}>${text}</button>`;
const input=(path,label,placeholder='',textarea=false)=>`<label class="field">${esc(label)}${textarea?`<textarea data-field="${path}" placeholder="${esc(placeholder)}">${esc(get(path)||'')}</textarea>`:`<input data-field="${path}" value="${esc(get(path)||'')}" placeholder="${esc(placeholder)}">`}</label>`;
const check=(path,label)=>`<label class="check"><input type="checkbox" data-field="${path}" ${get(path)?'checked':''}><span>${esc(label)}</span></label>`;
function picker(path,label,options){return `<label class="field">${esc(label)}<select data-field="${path}">${options.map(v=>`<option ${get(path)===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;}
function nav(){return [['defend','Defend me','◈'],['case','My case','◫'],['scenarios','If they say…','↳'],['notes','Notes','✎'],['sources','Sources','▤']].map(([id,label,icon])=>`<a href="#${id}" class="navlink ${route===id?'active':''}" ${route===id?'aria-current="page"':''}><span aria-hidden="true">${icon}</span><b>${label}</b></a>`).join('');}
function render(){const openKeys=[...document.querySelectorAll('#app details[open]')].map(e=>e.classList.contains('case-facts')?'case-facts':e.querySelector('summary')?.textContent);close();document.body.classList.toggle('source-mode',show);try{sessionStorage.setItem(MODE,String(show));}catch{}if(show){sourceView();return;}
const f=defence(),activeResponse=route==='defend'&&selected?response(selected):null;$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><a href="#defend" class="brand">RW<span>DEFENCE</span></a><div class="private-label">YOUR PRIVATE CORNER</div><nav aria-label="Main navigation">${nav()}</nav><div class="side-bottom">Truthful. Prepared. Composed.<br><button class="text-btn" data-action="more">Backup & more ↗</button></div></aside><div class="body"><header class="top"><span>DISCIPLINARY DEFENCE <em>Private workspace</em></span><div>${btn('Procedure problem','procedure','','quiet')}${btn('Show source','source-home','','quiet')}${btn('⋯','more','aria-label="Backup and more"','mobile-more quiet')}</div></header><div class="workspace"><main id="main">${loadError?`<div class="warning">${esc(loadError)}</div>`:''}${page()}</main><aside class="defence-aside"><div class="eyebrow">Your position · ${f.level}/5</div><h3>Best response</h3><p class="aside-response">${esc(activeResponse?.say||f.say)}</p><hr><div class="eyebrow amber">Biggest risk</div><p>${esc(activeResponse?.trap||f.risk)}</p><details><summary>How to handle it</summary><p>${esc(f.handle)}</p></details><button class="text-btn" data-action="sources" data-ids="${activeResponse?activeResponse.sources.join(','):f.source}">Key source ↗</button><hr>${btn('Before they come back','pause','','full')}${btn('Help me close','closing','','full quiet')}<div class="save"><i></i><span id="save-state">${saved?'Saved on this device':'Not saved · export'}</span><small id="offline">Checking offline…</small></div></aside></div></div><nav class="mobile-nav" aria-label="Mobile navigation">${nav()}</nav></div><div class="mobile-tools">${btn('Procedure problem','procedure','','quiet')}${btn('Pause / close','pause','','quiet')}</div>`;document.querySelectorAll('#app details').forEach(e=>{if(openKeys.includes(e.classList.contains('case-facts')?'case-facts':e.querySelector('summary')?.textContent))e.open=true;});updateOffline();}
function page(){if(route==='case')return casePage();if(route==='scenarios')return scenarios();if(route==='notes')return notesPage();if(route==='sources')return sourcesPage();if(route==='appeal')return appealPage();return home();}
function home(){return `${selected||searchOpen?'':`<div class="intro"><div class="eyebrow">Private · live meeting</div><h1>Defend me.</h1><p class="context">Allegation: Drinking during working hours<br><span>${d().incident?'Incident identified in your case notes':'Exact incident: Not yet confirmed'}</span></p></div>`}${searchOpen||selected?searchBox():`<section class="position"><div class="eyebrow">My position</div><p>${esc(defence().best)}</p></section><div class="hero-actions">${btn('What do I say? <span>↗</span>','search','','primary giant')}${btn('They’ve said something new <span>＋</span>','new','','giant')}${btn('Show me my defence <span>→</span>','case','','giant')}</div>`}${selected?responseCard(response(selected)):''}${searchOpen&&!selected?`<div id="matches">${matches(query)}</div>`:''}${selected?'':`<section class="emergencies"><div class="section-title">Emergency responses</div><div class="emergency-grid">${[['new-evidence','New evidence','I need reasonable time to consider this.'],['interrupted','Interrupted','Please let me finish my response.'],['gross','Gross misconduct','What facts and wording support that?'],['dismiss','Dismissal','Why dismissal rather than a lesser sanction?']].map(([id,title,line])=>`<button class="emergency" data-action="respond" data-id="${id}"><strong>${title}<span>↗</span></strong><small>${line}</small></button>`).join('')}</div></section><details class="key-points" ${!selected&&!searchOpen?'open':''}><summary>My 5 key points</summary><ol><li>Establish exactly which incident is alleged.</li><li>Do not guess or volunteer unrelated incidents.</li><li>A rule breach and gross misconduct are separate questions.</li><li>Ask for the evidence and specific risk supporting classification.</li><li>Acknowledge an established mistake; argue mitigation and a proportionate sanction.</li></ol></details>`}`;}
function searchBox(){return `<div class="live-search"><label for="live-query">What did they just say?</label><div class="query-wrap"><span>⌕</span><input id="live-query" value="${esc(query)}" placeholder="e.g. still working, CCTV, dismissal…" autocomplete="off" enterkeyhint="search"><button data-action="clear-search" aria-label="Clear response search">×</button></div><div class="fast-picks">${[['working','Still working'],['lockup','Lock-up'],['gross','Gross misconduct'],['cctv','CCTV'],['potential','Could be impaired'],['manager','Manager'],['dismiss','Dismissal']].map(([id,title])=>`<button data-action="respond" data-id="${id}">${title}</button>`).join('')}</div></div>`;}
function normal(text){return text.toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim();}
function results(text){const t=normal(text),words=t.split(' ').filter(w=>w.length>1&&!['you','were','the','are','have','they','this','that','said','was','we','your','been'].includes(w));return bank.map(r=>{const c=normal(r.claim),tags=normal(r.tags);let score=(c===t?100:0)+(t&&c.includes(t)?35:0)+words.reduce((a,w)=>a+(c.split(' ').includes(w)?6:0)+(tags.split(' ').includes(w)?4:0),0);if(t.includes('gross')&&r.id==='accept')score-=20;if(t.includes('witness')&&t.includes('drunk')&&r.id==='witnessdrunk')score+=50;if(/could.*(impair|affect)/.test(t)&&r.id==='potential')score+=50;if(/consider.*dismiss/.test(t)&&r.id==='dismiss')score+=35;if(t.includes('should know')&&r.id==='better')score+=30;return {r,score};}).filter(x=>!t||x.score>0).sort((a,b)=>b.score-a.score).slice(0,6).map(x=>x.r);}
function matches(text){if(!text.trim())return `<div class="section-title spaced">Most likely</div><div class="match-list">${['working','lockup','gross','cctv','potential','manager','dismiss'].map(id=>matchButton(bank.find(r=>r.id===id))).join('')}</div>`;return results(text).map(matchButton).join('')||`<p class="muted">No exact preset. Use a clarification response.</p>${matchButton(bank.find(r=>r.id==='other'))}`;}
function matchButton(r){return `<button class="match" data-action="respond" data-id="${r.id}"><span>${esc(r.claim)}</span><b>→</b></button>`;}
function responseCard(r){return `<article class="response" id="answer"><div class="they-said"><span>They say</span><h2>${esc(r.claim)}</h2>${btn('Change','search','','text-btn')}</div><div class="say"><div class="eyebrow">SAY</div><p id="say-text">${esc(r.say)}</p></div>${r.ask?`<div class="ask"><div class="eyebrow">ASK</div><p>${esc(r.ask)}</p></div>`:''}<details class="why"><summary>WHY <span>Source & private warning</span></summary><div class="private-warning"><b>Do not get caught by this</b><p>${esc(r.trap)}</p></div><p class="muted">${esc(r.why)}</p><div class="row">${btn('Show source','sources',`data-ids="${r.sources.join(',')}"`,'solid')}${btn('Copy response','copy-response',`data-id="${r.id}"`,'quiet')}</div></details><div class="response-tools">${btn('Pause / close','pause','','quiet')}${btn('＋ Log this claim','log-response',`data-id="${r.id}"`,'quiet')}${r.ask?btn('Track this question','question',`data-id="${r.id}"`,'quiet'):''}${r.id==='new-evidence'?btn('Request adjournment','log',`data-type="Adjournment requested" data-note="${esc(r.say)}"`,'solid'):''}${r.id==='dismissed'?btn('Record dismissal / appeal','outcome','','solid'):''}</div></article>`;}
function scenarios(){const cats=[...new Set(bank.map(r=>r.category))];return `<div class="page-title"><div class="eyebrow">Find your next sentence</div><h1>If they say…</h1></div>${searchBox()}<div id="scenario-results">${query?matches(query):cats.map(c=>`<details class="scenario-group"><summary>${esc(c)} <small>${bank.filter(r=>r.category===c).length}</small></summary>${bank.filter(r=>r.category===c).map(matchButton).join('')}</details>`).join('')}</div>`;}
function casePage(){const f=defence();return `<div class="page-title"><div class="eyebrow">Private · your recorded position</div><h1>My case</h1></div><section class="best"><div class="eyebrow">My best argument</div><h2 id="best-argument">${esc(f.best)}</h2></section><section class="risk"><div class="eyebrow">My biggest risk</div><p id="biggest-risk">${esc(f.risk)}</p><small id="risk-handle">${esc(f.handle)}</small></section><details class="case-facts"><summary>Update what is established <span>Defence level ${f.level}/5</span></summary>${check('defence.incident','The exact incident has been identified')}${input('defence.incidentDetail','Incident / allegation and source','Date, time, exact allegation or invitation reference',true)}<p class="micro">Your assessment drives these prompts. A claim alone does not establish a fact. Evidence status needs a source.</p>${checks.map(([k,l])=>`<div class="assessment">${picker(`defence.checks.${k}.status`,l,statuses)}${input(`defence.checks.${k}.source`,'Evidence / source','What supports this position?')}</div>`).join('')}${check('defence.errorAccepted','I have acknowledged an error of judgement')}${check('defence.promise','I can honestly commit not to repeat that conduct')}<div class="ladder" aria-label="Defence ladder">${['Incident / core facts not established','Consumption established','Policy breach established','Strong gross-misconduct evidence','Dismissal'].map((t,i)=>`<div class="${f.level===i+1?'current':''}"><b>${i+1}</b><span>${t}</span></div>`).join('')}</div><p class="micro">Position guide based on your entries, not a finding of liability. “Strong evidence” requires your confirmation and a source.</p></details><div class="case-editors">${input('defence.accept','What I currently accept','Only facts you accept',true)}${input('defence.dispute','What I dispute','Your actual disputed facts or classification',true)}${input('defence.explain','What they need to explain','The gaps that matter',true)}${input('defence.mitigate','My mitigation','Confirmed factors and the source for each',true)}${check('defence.mitigationRaised','I have raised this mitigation in the meeting')}</div><div class="row">${btn('Test my defence','test','','solid')}${btn('Before they come back','pause')}${btn('Help me close','closing')}${btn('Companion','companion')}${btn('Record outcome','outcome')}</div><details class="legacy"><summary>Existing case record & background</summary><p class="muted">Your previous case fields, evidence and mitigation have been preserved. They are not silently converted into new admissions.</p><div class="longtext">${esc(legacyText())}</div></details>`;}
function legacyText(){const facts=Object.entries(state.facts||{}).filter(([,v])=>v?.value).map(([k,v])=>`${k}: ${v.value} [${v.status||'Not established'}]`),ev=(state.evidence||[]).filter(e=>e.evidence||e.employer||e.employee).map(e=>`${e.issue}: ${e.evidence||e.employer||e.employee} [${e.status||'Unknown'}]`),mit=Object.entries(state.mitigation||{}).filter(([,v])=>v?.confirmed).map(([k,v])=>`${v.label||k}: ${v.evidence||'source not entered'}`);return [...facts,...ev,...mit].join('\n')||'No earlier substantive entries.';}
function notesPage(){return `<div class="page-title"><div class="eyebrow">Your private meeting record</div><h1>Notes</h1><span class="micro">Automatic timestamps · saved on this device</span></div><div class="note-chips">${['Claim','Evidence','My response','New allegation','Adjournment requested','Refused','Mitigation','Outcome'].map(t=>btn('+ '+t,'log',`data-type="${t}"`,'quiet')).join('')}</div>${input('notes','Meeting notes','Type what matters. Notes are not sent anywhere.',true)}<div class="row">${btn('Copy','copy-notes')}${btn('Print','print-notes')}${btn('Export','export-notes')}</div>${state.log.length?`<div class="section-title spaced">Meeting memory</div><div class="memory">${state.log.slice().reverse().map(e=>`<article><time>${stamp(e.created)}</time><div><strong>${esc(e.type)}</strong><p>${esc(e.note)}</p>${e.edited?'<small>Edited; original timestamp retained</small>':''}</div>${btn('Edit','edit-log',`data-id="${e.id}"`,'text-btn')}</article>`).join('')}</div>`:'<p class="empty">Tap a category when a point needs a timestamp.</p>'}${state.questions.length?`<details class="spaced"><summary>Questions I am tracking</summary>${state.questions.map((q,i)=>`${check(`questions.${i}.answered`,q.question||q.text||'Question')}${input(`questions.${i}.answer`,'Answer / response received')}`).join('')}</details>`:''}`;}
function sourcesPage(){return `<div class="page-title"><div class="eyebrow">Exact wording, when you need it</div><h1>My backup</h1><p class="muted">Ten useful references. Tap to show the source.</p></div><div class="backup-list">${window.RW_BACKUP.map(([title,ids],i)=>`<button data-action="sources" data-ids="${ids.join(',')}"><small>${String(i+1).padStart(2,'0')}</small><span>${title}</span><b>↗</b></button>`).join('')}</div><button class="text-btn spaced" data-action="source-search">Search all source text →</button>`;}
function sourceView(){const selectedSources=sourceIds.map(id=>quotes.find(q=>q.id===id)||laws.find(l=>l.id===id)).filter(Boolean);$('#app').innerHTML=`<div class="source-shell"><header class="source-header"><div><div class="eyebrow">ROCKWATER · SOURCE VIEW</div><h1>Source wording</h1></div>${btn('Return to defence','return','','solid')}</header><main id="main">${sourceIds.length?`<div class="source-controls">${btn('Choose another source','source-home','','quiet')}${btn('Print this source','print','','quiet')}</div>${selectedSources.map(sourceCard).join('')}`:`<div class="backup-list">${window.RW_BACKUP.map(([t,ids])=>`<button data-action="sources" data-ids="${ids.join(',')}"><span>${t}</span><b>↗</b></button>`).join('')}</div><button class="text-btn spaced" data-action="source-search">Search all source text</button>`}</main></div>`;}
function sourceCard(s){const doc=docs.find(d=>d.id===s.doc);return `<article class="source-card"><div class="eyebrow">${s.doc?'Exact quote':'Official guidance · summary'}</div><h2>${esc(s.title||s.heading)}</h2>${s.doc?`<blockquote>${esc(s.text)}</blockquote>`:`<p class="legal-summary">${esc(s.summary)}</p>${s.note?`<p class="muted">${esc(s.note)}</p>`:''}`}<div class="source-meta">${esc(doc?.title||s.kind)}<br>${esc(s.doc?`${s.section}${s.page?' · page '+s.page:''}`:s.paragraph)} · Checked ${esc(s.verified||'2026-10-08')}</div>${s.doc?`<details><summary>Surrounding source context</summary><p class="source-context">${esc(s.context||s.text)}</p>${s.note?`<p class="micro">${esc(s.note)}</p>`:''}</details>`:`<a href="${safeURL(s.url)}" target="_blank" rel="noopener noreferrer">Official source ↗</a>${s.additionalUrl?` · <a href="${safeURL(s.additionalUrl)}" target="_blank" rel="noopener noreferrer">Supporting source ↗</a>`:''}`}${btn('Copy source','copy-source',`data-id="${esc(s.id)}"`,'text-btn')}</article>`;}
function showSources(ids){sourceOrigin=route;sourceIds=ids;show=true;render();window.scrollTo(0,0);}
function safeURL(url){try{const u=new URL(url);return u.protocol==='https:'?esc(u.href):'#';}catch{return '#';}}
function close(){const e=$('#overlay');if(e)e.innerHTML='';overlayType='';}
function modal(title,html,type=''){lastFocus=document.activeElement;overlayType=type;$('#overlay').innerHTML=`<div class="backdrop" data-action="close"></div><section role="dialog" aria-modal="true" aria-label="${esc(title)}" class="modal"><header><h2>${esc(title)}</h2><button data-action="close" class="x" aria-label="Close">×</button></header>${html}</section>`;setTimeout(()=>$('#overlay input,#overlay textarea,#overlay button')?.focus(),20);}
function noteDialog(type,note='',id=''){modal(id?'Edit meeting event':'Record '+type,`<p class="micro">Private employee record · ${id?'original timestamp retained':'timestamped when saved'}</p><label class="field">${esc(type)}<textarea id="event-text" placeholder="What was said, produced or answered?">${esc(note)}</textarea></label><div class="row">${btn('Save to meeting memory','save-log',`data-type="${esc(type)}" data-id="${esc(id)}"`,'solid')}${btn('Cancel','close','','quiet')}</div>`,'note');setTimeout(()=>$('#event-text')?.focus(),20);}
function procedure(){modal('Procedure problem',`<div class="problem-grid">${[['new-evidence','New evidence'],['new-allegation','New allegation'],['time','No time to prepare'],['interrupted','Interrupted'],['no-response','Not allowed to respond'],['refused','Adjournment refused'],['companion','Companion refused'],['ignored','Mitigation ignored'],['predecided','Appears predecided'],['other','Other']].map(([id,l])=>btn(l,'problem',`data-id="${id}"`)).join('')}</div>`);}
function pause(){const f=defence(),qs=state.questions.filter(q=>!q.answered);modal('Before they come back',`<div class="pause-grid"><section><div class="eyebrow amber">Biggest risk</div><p>${esc(f.risk)}</p></section><section><div class="eyebrow">Best argument</div><p>${esc(f.best)}</p></section></div><div class="section-title spaced">Unanswered questions</div><ul>${qs.length?qs.map(q=>`<li>${esc(q.question||q.text)}</li>`).join(''):'<li>No tracked unanswered questions. Check your notes.</li>'}</ul><div class="section-title spaced">Mitigation not yet said</div><p>${esc(d().mitigate&&!d().mitigationRaised?d().mitigate:'No unsaid mitigation recorded. Do not invent a positive factor.')}</p><div class="section-title spaced">Top 3 before a decision</div><ol><li>${esc(f.say)}</li><li>${esc(qs[0]?.question||'What specific evidence supports the classification and proposed sanction?')}</li><li>${esc(d().mitigate&&!d().mitigationRaised?'Raise the mitigation you have recorded.':'Ask whether a lesser sanction is sufficient.')}</li></ol><div class="row">${btn('Help me close','closing','','solid')}${btn('Log adjournment','log','data-type="Meeting adjourned"')}${btn('Companion view','companion')}</div>`);}
function testDefence(){modal('Test my defence',`<div class="eyebrow">Private · strongest counter</div><h3>“Active service had finished” is not enough on its own.</h3><div class="test-questions">${['Were you clocked in or being paid?','Did lock-up or staff supervision remain?','Could you leave the premises?','Who decided when your shift ended?','What actual permission and staff-drink instruction applied?'].map(t=>`<p>• ${t}</p>`).join('')}</div><div class="risk"><b>Weakness</b><p>Remaining duties can support working time. Potential impairment can support gross misconduct even without actual harm.</p></div><div class="say compact"><div class="eyebrow">Best honest response</div><p>${esc(defence().level>=3?defence().say:'Do not overclaim that you were off duty. Accept responsibilities established by reliable evidence, then address classification and sanction separately.')}</p></div><details><summary>Other holes to check</summary><p>Do not claim permission merely because you were the manager. Do not claim an isolated mistake or clean record without checking earlier matters. The gross-misconduct list is not exhaustive, and serious safety provisions may apply independently.</p></details><div class="row">${btn('Update my case','case','','solid')}${btn('Check supporting wording','sources','data-ids="security,hours,alcohol-gross-disciplinary,complimentary-drinks,serious-safety,gross-nonexhaustive"')}</div>`);}
function companion(){const f=defence();modal('Companion · private view',`<div class="eyebrow">My position</div><p>${esc(f.best)}</p><div class="eyebrow amber spaced">Biggest risk</div><p>${esc(f.risk)}</p><div class="eyebrow spaced">Top questions</div><ul>${state.questions.filter(q=>!q.answered).slice(0,3).map(q=>`<li>${esc(q.question||q.text)}</li>`).join('')||'<li>What evidence supports the classification and sanction?</li>'}</ul><div class="eyebrow spaced">Mitigation</div><p>${esc(d().mitigate||'No confirmed mitigation entered.')}</p><div class="row spaced">${btn('Take notes','notes','','solid')}${btn('Companion rights','sources','data-ids="law-companion,law-companion-role,law-postponement,companion"')}</div><p class="micro spaced">Private preparation view. Use Source view to show management the rights alone.</p>`);}
function outcome(){modal('Record the outcome',`${picker('defence.sanction','Outcome stated',['Not given','Pending','No action','First written warning','Final written warning','Other sanction','Dismissal'])}${input('defence.decisionDate','Decision date','YYYY-MM-DD')}${input('defence.outcomeReason','Findings, reasons and evidence relied on','Record the employer’s words',true)}${input('defence.effectiveDate','Effective date / notice position')}${input('defence.appealDeadline','Deadline / recipient communicated')}<p class="micro">Rockwater says appeal in writing within 5 working days of the decision. Confirm the date, bank holidays and recipient. Internal and tribunal deadlines differ.</p><div class="row">${btn('Save outcome','save-outcome','','solid')}${btn('Open appeal','appeal')}${btn('Show appeal wording','sources','data-ids="appeal"')}</div>`,'outcome');}
const appealFields=[['finding','What they found'],['dispute','What I dispute'],['evidence','Evidence problem'],['procedure','Procedural problem'],['mitigation','Mitigation'],['consistency','Consistency'],['proportionality','Proportionality'],['new','New evidence']];
function appealDraft(){const items=appealFields.filter(([id])=>d().appealGrounds[id]?.selected&&d().appealGrounds[id]?.text?.trim()&&d().appealGrounds[id]?.source?.trim());if(!items.length)return 'Select a ground and enter its explanation and supporting source. No grounds will be invented.';return `I wish to appeal ${d().outcomeReason?'the decision recorded as: '+d().outcomeReason:'the disciplinary decision'}${d().decisionDate?' dated '+d().decisionDate:''}.\n\n`+items.map(([id,label])=>`${label}: ${d().appealGrounds[id].text}\nSupporting source: ${d().appealGrounds[id].source}`).join('\n\n')+`\n\n${d().appealRequest||'Please reconsider the decision and confirm the appeal arrangements.'}`;}
function appealPage(){return `<div class="page-title"><div class="eyebrow">After the decision</div><h1>Appeal</h1><p class="muted">Written appeal within 5 working days of the decision: confirm your actual deadline.</p></div><div class="row">${btn('Record decision / deadline','outcome')}${btn('Show appeal wording','sources','data-ids="appeal"')}</div><div class="spaced">${appealFields.map(([id,label])=>`<section class="appeal-ground">${check(`defence.appealGrounds.${id}.selected`,label)}${d().appealGrounds[id]?.selected?input(`defence.appealGrounds.${id}.text`,'Your factual point','State what happened and why you challenge it',true)+input(`defence.appealGrounds.${id}.source`,'Supporting evidence / source','Required to include this ground'):''}</section>`).join('')}</div>${input('defence.appealRequest','Requested outcome','The change you want')}<details open><summary>Draft for your review</summary><p class="micro">Only selected grounds with an explanation and source are included.</p><div id="appeal-draft" class="longtext">${esc(appealDraft())}</div><div class="row spaced">${btn('Update draft','refresh')}${btn('Copy draft','copy-appeal')}</div></details>`;}
function sourceSearch(){modal('Search the source text',`<input class="search-input" id="source-query" value="${esc(sourceQuery)}" placeholder="Search a word or phrase…" aria-label="Search source text"><div id="source-results">${sourceResults(sourceQuery)}</div>`,'sources');setTimeout(()=>$('#source-query')?.focus(),20);}
function sourceResults(text){const terms=normal(text).split(' ').filter(Boolean),match=t=>terms.every(w=>normal(t).includes(w));if(!terms.length)return '<p class="empty">Only document wording and official reference material are searched.</p>';const qs=quotes.filter(q=>match(q.text+' '+q.title)),ls=laws.filter(l=>match(l.summary+' '+l.title)),ss=docs.flatMap(doc=>doc.sections.filter(s=>match(s.text)).slice(0,5).map(s=>({doc,s}))).slice(0,12);return qs.slice(0,12).concat(ls.slice(0,6)).map(q=>`<button class="match" data-action="sources" data-ids="${q.id}"><span>${esc(q.title||q.heading)}</span>↗</button>`).join('')+ss.map(({doc,s})=>`<button class="match" data-action="section" data-doc="${doc.id}" data-section="${s.id}"><span>${esc(doc.title)} · ${esc(s.heading)} (${s.id})</span>↗</button>`).join('')||'<p class="empty">No match in the supplied text. Try a shorter word.</p>';}
function allText(){return ['PRIVATE DISCIPLINARY DEFENCE RECORD',stamp(now()),'','MY ACCEPTED FACTS',d().accept,'','MY DISPUTED POINTS',d().dispute,'','WHAT THEY NEED TO EXPLAIN',d().explain,'','MY MITIGATION',d().mitigate,'','NOTES',state.notes,'','MEETING MEMORY',...state.log.map(e=>`${stamp(e.created)} | ${e.type}\n${e.note}`),'','QUESTIONS',...state.questions.map(q=>`${q.answered?'Answered':'Unanswered'}: ${q.question||q.text}\n${q.answer||''}`),'','OUTCOME',d().sanction,d().outcomeReason||'','Decision date: '+(d().decisionDate||'Not entered'),'','EARLIER CASE RECORD',legacyText()].join('\n');}
function more(){modal('Backup & more',`<div class="more-grid">${btn('Export JSON backup','backup','','solid')}${btn('Import backup','import')}${btn('Export meeting record','export-notes')}${btn('Attach original locally','attach')}${btn('Companion view','companion')}${btn('Appeal workspace','appeal')}</div><input type="file" id="import-file" accept=".json" hidden><input type="file" id="original-file" accept=".pdf,.docx,.txt,.png,.jpg" hidden><p class="micro spaced">Case data is local to this browser. Backups are private and unencrypted. Original files remain in this browser’s IndexedDB and are not included in JSON backups.</p><p class="micro" id="cache-status">Checking offline readiness…</p>${state.attachments.map(a=>`<div class="file-row"><span>${esc(a.name)}</span>${btn('Open','open-file',`data-id="${a.id}"`,'quiet')}</div>`).join('')}<details class="spaced"><summary>Sources, previous work & privacy</summary><p class="micro">Previous case data is preserved in your backup and My case. The website is public; entered notes are not uploaded. Share mode is a presentation boundary, not encryption or access control.</p><div class="row"><a href="README.md" target="_blank">Guide</a><a href="SOURCE-AUDIT.md" target="_blank">Source audit</a><a href="disciplinary-quick-reference.html" target="_blank">Printable source backup</a></div></details><button class="text-btn danger spaced" data-action="clear">Clear this local case</button>`,'more');updateOffline();}
function notice(text){const t=$('#toast');t.textContent=text;t.classList.add('visible');clearTimeout(notice.timer);notice.timer=setTimeout(()=>t.classList.remove('visible'),3500);}
async function copy(text){try{await navigator.clipboard.writeText(text);notice('Copied');}catch{modal('Copy this text',`<textarea id="copy-text">${esc(text)}</textarea>`);$('#copy-text').select();}}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:name.endsWith('.json')?'application/json':'text/plain'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
async function db(mode,fn){const database=await new Promise((res,rej)=>{const r=indexedDB.open('rwdef.files.v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});return new Promise((res,rej)=>{const tx=database.transaction('files',mode),r=fn(tx.objectStore('files'));let v;r.onsuccess=()=>v=r.result;tx.oncomplete=()=>{database.close();res(v);};tx.onerror=()=>{database.close();rej(tx.error);};});}
function validate(x){if(x?.version!==1||typeof x.notes!=='string'||!Array.isArray(x.log))throw Error('Not a supported case backup');const scan=(o,depth=0)=>{if(depth>20)throw Error('Backup nesting too deep');if(o&&typeof o==='object')for(const [k,v]of Object.entries(o)){if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe backup key');scan(v,depth+1);}};scan(x);for(const e of x.log)if(typeof e.type!=='string'||typeof e.note!=='string'||!Number.isFinite(Date.parse(e.created)))throw Error('Invalid meeting event');if(x.defence){for(const k of ['accept','dispute','explain','mitigate','incidentDetail','sanction','outcomeReason','decisionDate','effectiveDate','appealDeadline','appealRequest'])if(x.defence[k]!==undefined&&typeof x.defence[k]!=='string')throw Error('Invalid defence text');for(const k of ['incident','promise','errorAccepted','mitigationRaised'])if(x.defence[k]!==undefined&&typeof x.defence[k]!=='boolean')throw Error('Invalid confirmation');for(const k of ['checks','appealGrounds'])if(x.defence[k]&&(!x.defence[k]||typeof x.defence[k]!=='object'||Array.isArray(x.defence[k])))throw Error('Invalid defence assessment');}for(const k of ['log','questions','evidence','attachments'])if(x[k]&&(!Array.isArray(x[k])||x[k].some(v=>!v||typeof v!=='object'||Array.isArray(v))))throw Error('Invalid records');if(x.defence&&(typeof x.defence!=='object'||Array.isArray(x.defence)))throw Error('Invalid defence record');if(x.defence?.checks)for(const v of Object.values(x.defence.checks))if(!v||!statuses.includes(v.status)||typeof v.source!=='string')throw Error('Invalid fact assessment');return x;}
async function act(el){const a=el.dataset.action;if(show&&!['return','sources','source-home','source-search','section','close','print','copy-source'].includes(a))return;
if(a==='close'){close();lastFocus?.focus();}
else if(a==='case'||a==='notes'||a==='appeal'){route=a;location.hash=a;render();window.scrollTo(0,0);}
else if(a==='search'){searchOpen=true;selected='';query='';if(route!=='scenarios')route='defend';render();$('#live-query')?.focus();}
else if(a==='clear-search'){query='';selected='';searchOpen=true;render();$('#live-query')?.focus();}
else if(a==='respond'){selected=el.dataset.id;searchOpen=true;query='';route='defend';location.hash='defend';render();$('#answer')?.scrollIntoView({block:'start'});}
else if(a==='new')modal('What changed?',`<div class="problem-grid">${btn('New claim / argument','search','','solid')}${btn('New evidence','problem','data-id="new-evidence"')}${btn('New allegation','problem','data-id="new-allegation"')}${btn('Update established facts','case')}</div>`);
else if(a==='sources')showSources(el.dataset.ids.split(','));
else if(a==='source-home'){show=true;sourceIds=[];render();window.scrollTo(0,0);}
else if(a==='return'){show=false;render();if(selected)$('#answer')?.scrollIntoView({block:'start'});}
else if(a==='source-search'){sourceQuery='';sourceSearch();}
else if(a==='section'){const doc=docs.find(d=>d.id===el.dataset.doc),s=doc.sections.find(s=>s.id===el.dataset.section);show=true;sourceIds=[];render();modal(s.heading,`<p class="micro">${esc(doc.title)} · ${esc(s.id)}${s.page?' · page '+s.page:''}</p><div class="source-context">${esc(s.text)}</div>`,'source-section');}
else if(a==='copy-source'){const q=quotes.find(q=>q.id===el.dataset.id)||laws.find(l=>l.id===el.dataset.id);copy((q.text||'Summary: '+q.summary)+'\n'+(q.doc?docs.find(d=>d.id===q.doc).title+' · '+q.section:q.url));}
else if(a==='procedure')procedure();
else if(a==='problem'){const r=response(el.dataset.id);modal(r.claim,`<div class="say compact"><div class="eyebrow">SAY</div><p>${esc(r.say)}</p></div><div class="row">${btn('Timestamp concern','log',`data-type="Procedural issue" data-note="${esc(r.claim+': '+r.say)}"`,'solid')}${btn('Show source','sources',`data-ids="${r.sources.join(',')}"`)}</div>${r.id==='new-evidence'?`<div class="row spaced">${btn('Request adjournment','log',`data-type="Adjournment requested" data-note="${esc(r.say)}"`)}${btn('Refused','problem','data-id="refused"')}</div>`:''}<details class="spaced"><summary>Private warning</summary><p>${esc(r.trap)}</p></details>`);}
else if(a==='pause')pause();
else if(a==='test')testDefence();
else if(a==='closing')modal('Your 30-second close',`<div class="say compact"><div class="eyebrow">SAY</div><p id="closing-text">${esc(closing())}</p></div><p class="micro">${closing().split(/\s+/).length} words · generated only from your recorded position and commitments.</p><div class="row">${btn('Copy','copy-closing','','solid')}${btn('Log my response','log',`data-type="My response" data-note="${esc(closing())}"`)}</div>`);
else if(a==='companion')companion();
else if(a==='outcome')outcome();
else if(a==='save-outcome'){log('Outcome',`${d().sanction}: ${d().outcomeReason||'Reasons not entered'}`);render();if(d().sanction==='Dismissal')modal('Protect your position now',`<div class="say compact"><p>Please provide the findings, reasons and appeal instructions in writing. I am not resigning.</p></div><ol><li>Get the findings and evidence relied on.</li><li>Record the effective date and preserve your notes.</li><li>Confirm the written appeal deadline: 5 working days from the decision under the handbook.</li></ol><div class="row">${btn('Open appeal','appeal','','solid')}${btn('Export record','export-notes')}</div>`);else notice('Outcome recorded');}
else if(a==='refresh'){save();render();}
else if(a==='copy-appeal')copy(appealDraft());
else if(a==='copy-closing')copy(closing());
else if(a==='copy-response'){const r=response(el.dataset.id);copy(r.say+(r.ask?'\n\nASK: '+r.ask:''));}
else if(a==='question'){const r=response(el.dataset.id);if(!state.questions.some(q=>q.question===r.ask&&!q.answered)){state.questions.push({id:uid(),question:r.ask,answered:false,answer:'',created:now()});save();}notice('Question tracked');}
else if(a==='log-response'){const r=response(el.dataset.id);noteDialog('Claim',r.claim);}
else if(a==='log')noteDialog(el.dataset.type,el.dataset.note||'');
else if(a==='edit-log'){const e=state.log.find(e=>e.id===el.dataset.id);noteDialog(e.type,e.note,e.id);}
else if(a==='save-log'){const text=$('#event-text').value;if(el.dataset.id){const e=state.log.find(e=>e.id===el.dataset.id);e.note=text;e.edited=now();save();}else log(el.dataset.type,text);render();notice('Meeting memory updated');}
else if(a==='copy-notes')copy(allText());
else if(a==='export-notes')download('rwdef-meeting-record.txt',allText());
else if(a==='print-notes'){modal('Private meeting record',`<div class="longtext">${esc(allText())}</div><div class="row">${btn('Print private record','print','','solid')}</div>`,'print-notes');}
else if(a==='print')window.print();
else if(a==='more')more();
else if(a==='backup'){download('rwdef-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(state,null,2));}
else if(a==='import')$('#import-file').click();
else if(a==='restore'){const attachments=state.attachments;state=validate(pendingImport);state.attachments=attachments;defaults();pendingImport=null;loadError='';save();render();notice('Backup restored; original files kept on device');}
else if(a==='attach')$('#original-file').click();
else if(a==='open-file'){const f=await db('readonly',s=>s.get(el.dataset.id));if(!f)throw Error('Original unavailable. Attach the file again.');const url=URL.createObjectURL(f.file);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}
else if(a==='clear')modal('Clear this local case?',`<p>Export a backup first. Case notes and attached originals will be removed from this browser.</p><label class="field spaced">Type CLEAR<input id="confirm-clear"></label><div class="row">${btn('Export backup','backup')}${btn('Clear case','confirm-clear','','danger')}</div>`);
else if(a==='confirm-clear'){if($('#confirm-clear').value!=='CLEAR')return notice('Type CLEAR to confirm');await db('readwrite',s=>s.clear());localStorage.removeItem(KEY);sessionStorage.removeItem(MODE);location.hash='defend';location.reload();}}
document.addEventListener('click',e=>{const nav=e.target.closest('.navlink');if(nav?.getAttribute('href')==='#defend'&&!show){e.preventDefault();selected='';query='';searchOpen=false;route='defend';location.hash='defend';render();window.scrollTo(0,0);return;}const el=e.target.closest('[data-action]');if(el){e.preventDefault();act(el).catch(err=>notice('Could not complete: '+err.message));}});
document.addEventListener('input',e=>{const el=e.target;if(el.id==='source-query'){sourceQuery=el.value;$('#source-results').innerHTML=sourceResults(el.value);return;}if(show)return;if(el.id==='live-query'){query=el.value;selected='';let target=$('#matches')||$('#scenario-results');if(!target){$('#answer')?.remove();target=document.createElement('div');target.id='matches';$('.live-search').after(target);}target.innerHTML=matches(query);return;}if(el.dataset.field){put(el.dataset.field,el.type==='checkbox'?el.checked:el.value);save();}});
document.addEventListener('change',async e=>{const el=e.target;if(show)return;if(el.dataset.field){put(el.dataset.field,el.type==='checkbox'?el.checked:el.value);save();if(el.tagName==='SELECT'&&el.dataset.field.startsWith('defence.checks.')){log('My position updated',`${el.dataset.field.split('.')[2]}: ${el.value}. ${get(el.dataset.field.replace('.status','.source'))||'Source not entered'}`);}if(el.type==='checkbox'||el.tagName==='SELECT'){if(overlayType==='outcome')return;render();}}
if(el.id==='import-file'&&el.files[0])try{if(el.files[0].size>10e6)throw Error('Backup must be under 10 MB');pendingImport=validate(JSON.parse(await el.files[0].text()));modal('Restore this backup?',`<p>This replaces your current case. Your existing attached originals remain on this device.</p><div class="row spaced">${btn('Export current case','backup')}${btn('Restore backup','restore','','solid')}</div>`);}catch(err){notice(err.message);}
if(el.id==='original-file'&&el.files[0])try{const f=el.files[0];if(f.size>30e6)throw Error('Choose a file under 30 MB');const id=uid();await db('readwrite',s=>s.put({id,file:f}));state.attachments.push({id,name:f.name,size:f.size,added:now()});save();more();notice('File saved locally');}catch(err){notice(err.message);}});
document.addEventListener('focusout',e=>{if(show||!e.target.dataset.field)return;const path=e.target.dataset.field;if(path.startsWith('defence.')&&route==='case'){const f=defence();if($('#best-argument'))$('#best-argument').textContent=f.best;if($('#biggest-risk'))$('#biggest-risk').textContent=f.risk;if($('#risk-handle'))$('#risk-handle').textContent=f.handle;const ar=$('.aside-response');if(ar)ar.textContent=f.say;const side=$('.defence-aside');if(side){const risk=side.querySelector('.eyebrow.amber+p');if(risk)risk.textContent=f.risk;}document.querySelectorAll('.ladder>div').forEach((el,i)=>el.classList.toggle('current',i+1===f.level));}if($('#appeal-draft'))$('#appeal-draft').textContent=appealDraft();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();lastFocus?.focus();}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='s'){e.preventDefault();show=true;sourceIds=[];render();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(show)sourceSearch();else{searchOpen=true;selected='';route='defend';render();$('#live-query').focus();}}if(e.key==='Enter'&&e.target.id==='live-query'){const r=results(query)[0];if(r){selected=r.id;render();$('#answer')?.scrollIntoView({block:'start'});}}if(e.key==='Tab'&&$('#overlay [role="dialog"]')){const ns=[...$('#overlay').querySelectorAll('button,a,input,textarea,select,summary')].filter(n=>n.offsetParent!==null),first=ns[0],last=ns.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
const aliases={home:'defend',responses:'scenarios',facts:'case',account:'case',mitigation:'case',log:'notes',documents:'sources',legal:'sources',alcohol:'sources',settings:'defend'};
function hashRoute(){const hash=location.hash.slice(1);return aliases[hash]||(['defend','case','scenarios','notes','sources','appeal'].includes(hash)?hash:'defend');}
window.addEventListener('hashchange',()=>{route=hashRoute();render();if(selected&&route==='defend')$('#answer')?.scrollIntoView({block:'start'});else window.scrollTo(0,0);});
async function updateOffline(){let text='Open online once to prepare offline access.';try{const reg=await navigator.serviceWorker?.getRegistration();const keys=await caches.keys();if(reg?.active&&keys.some(k=>k.startsWith('rwdef-v2')))text='Offline ready';}catch{text='Offline cache unavailable';}if($('#offline'))$('#offline').textContent=text;if($('#cache-status'))$('#cache-status').textContent=text;}
window.addEventListener('beforeprint',()=>{document.querySelectorAll('.print-value').forEach(e=>e.remove());document.querySelectorAll('textarea').forEach(el=>{const p=document.createElement('div');p.className='print-value';p.textContent=el.value;el.after(p);});document.body.classList.toggle('printing-modal',!!$('#overlay [role="dialog"]'));});
window.addEventListener('afterprint',()=>{document.querySelectorAll('.print-value').forEach(e=>e.remove());document.body.classList.remove('printing-modal');});
route=hashRoute();render();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(async reg=>{await navigator.serviceWorker.ready;updateOffline();reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',updateOffline));}).catch(()=>updateOffline());
window.addEventListener('online',updateOffline);window.addEventListener('offline',updateOffline);
})();
