/* Official-source reference snapshot. Summaries are not quotations or case findings. */
(function () {
  'use strict';
  const verified = '2026-10-07';
  const code = 'https://www.acas.org.uk/acas-code-of-practice-on-disciplinary-and-grievance-procedures/html';
  const hearing = 'https://www.acas.org.uk/disciplinary-procedure-step-by-step/step-4-the-disciplinary-hearing';
  const outcome = 'https://www.acas.org.uk/disciplinary-procedure-step-by-step/step-5-deciding-on-the-disciplinary-outcome';
  const companion = 'https://www.legislation.gov.uk/ukpga/1999/26/section/10';
  window.RW_LEGAL = [
    {id:'acas-current',title:'Current Acas Code',summary:'The official published Code is dated 11 March 2015. Acas is consulting on an update; a consultation draft is not the current Code. These summaries use the published Code.',url:'https://www.acas.org.uk/acas-code-of-practice-on-disciplinary-and-grievance-procedures',kind:'ACAS CODE',force:'REFERENCE',paragraph:'Publication and Updates to this Code'},
    {id:'acas-consistency',title:'Clear rules and consistency',summary:'Rules should be clear; employers and employees should act consistently and address issues fairly.',url:code,kind:'ACAS CODE',force:'SHOULD',paragraph:'Paragraphs 2–4'},
    {id:'acas-investigation',title:'Establish the facts',summary:'Investigate promptly. Where practicable, use different investigators and hearing decision-makers. Investigation meetings alone should not impose discipline.',url:code,kind:'ACAS CODE',force:'SHOULD',paragraph:'Paragraphs 5–7'},
    {id:'acas-notice',title:'Notice and preparation',summary:'Give written allegations and possible consequences; normally include written evidence and statements. Allow reasonable preparation time; explain accompaniment.',url:code,kind:'ACAS CODE',force:'SHOULD',paragraph:'Paragraphs 9–11'},
    {id:'acas-hearing',title:'Answer the case',summary:'Explain allegations and evidence; allow answers, questions, evidence, relevant witnesses and comments on witness information. Give witness notice beforehand.',url:code,kind:'ACAS CODE',force:'SHOULD',paragraph:'Paragraph 12'},
    {id:'acas-sanctions',title:'Decision and sanctions',summary:'Decide after hearing; confirm in writing. Serious first misconduct can justify a final warning; gross misconduct can justify first-offence dismissal, following fair procedure.',url:code,kind:'ACAS CODE',force:'SHOULD / MAY',paragraph:'Paragraphs 18–24'},
    {id:'acas-appeal',title:'Impartial appeal',summary:'Give written appeal grounds promptly. Hear impartially, preferably through someone previously uninvolved; confirm the result in writing.',url:code,kind:'ACAS CODE',force:'SHOULD',paragraph:'Paragraphs 26–29'},
    {id:'acas-suspension',title:'Investigatory suspension',summary:'Paid investigatory suspension should be brief, reviewed and expressly distinguished from disciplinary action.',url:code,kind:'ACAS CODE',force:'SHOULD',paragraph:'Paragraph 8'},
    {id:'law-companion',title:'Right to an eligible companion',summary:'A worker who reasonably requests accompaniment at a qualifying disciplinary hearing must be allowed one chosen companion: another worker of the employer, an employed union official, or a union official certified in writing by the union as trained or experienced. There is no minimum-service requirement in section 10.',url:companion,kind:'OFFICIAL LAW',force:'MUST',paragraph:'Employment Relations Act 1999, section 10(1), (2A), (3)'},
    {id:'law-companion-role',title:'What a companion can do',summary:'The companion must be allowed to put and sum up the case, respond to views, and confer with the worker. The employer need not allow them to answer questions for the worker, speak against the worker’s wishes, or prevent others contributing.',url:companion,kind:'OFFICIAL LAW',force:'MUST',paragraph:'Employment Relations Act 1999, section 10(2B)–(2C)'},
    {id:'law-postponement',title:'Companion unavailable: postponement',summary:'If the chosen companion is unavailable, the employer must postpone to the worker’s proposed reasonable alternative time within the five-working-day period starting on the first working day after the employer’s proposed date.',url:companion,kind:'OFFICIAL LAW',force:'MUST',paragraph:'Employment Relations Act 1999, section 10(4)–(5)',note:'This rule concerns companion availability. It does not automatically decide a request for time to consider late evidence or all questions of fairness.'},
    {id:'acas-companion-scope',title:'Qualifying hearings and other companions',summary:'The right covers hearings that could issue or confirm formal disciplinary action, including appeals. There is no automatic statutory right to a solicitor simply because it is a disciplinary hearing. An employer may allow a wider companion; disability-related reasonable adjustments may require additional support.',url:hearing,kind:'ACAS GUIDANCE',force:'RIGHT / CONTEXT',paragraph:'The right to be accompanied',additionalUrl:code,additionalParagraph:'Paragraphs 13–17 and 28'},
    {id:'acas-late-evidence',title:'New evidence or a new allegation',summary:'Acas says allegations, evidence and possible outcomes should be supplied in good time and the employee allowed reasonable preparation. Request sufficient time to review new material, explain what you need to check, and record the response. An adjournment request is not automatically granted in every case.',url:hearing,kind:'ACAS GUIDANCE',force:'SHOULD',paragraph:'Preparing for the hearing',note:'The suggested request is a practical application of the preparation guidance, not a separate unconditional statutory right.'},
    {id:'acas-deliberation',title:'Consider the case before deciding',summary:'The employer should allow time after the hearing to consider the case carefully and explain the next steps. The hearing is an opportunity for both sides to present their positions before a decision.',url:hearing,kind:'ACAS GUIDANCE',force:'SHOULD',paragraph:'At the end of the hearing'},
    {id:'acas-proportionality',title:'Sanction, consistency and alternatives',summary:'The outcome should reflect the investigation and hearing, fairness and reasonableness, and similar earlier cases. Lesser outcomes can include informal action or warnings. Before other penalties such as demotion, check contractual permission and discuss the proposal. Gross misconduct may justify dismissal; the label does not remove the need for a fair process.',url:outcome,kind:'ACAS GUIDANCE',force:'SHOULD / MAY',paragraph:'Deciding the outcome; Taking other disciplinary action; Dismissal'},
    {id:'acas-warning',title:'Clarify any warning relied on',summary:'A written warning should explain the conduct, required change and timescale, consequences of repetition, and how long it stays current. Establish the document, level, dates, status and proposed relevance of any earlier warning.',url:outcome,kind:'ACAS GUIDANCE',force:'SHOULD',paragraph:'Written warnings',note:'The request to establish relevance is a factual preparation suggestion; it does not declare lateness warnings irrelevant.'},
    {id:'acas-outcome',title:'Get the decision in writing',summary:'The employer should provide the outcome promptly in writing. Dismissal should be decided by an authorised manager, with reasons, termination date, notice information and appeal rights explained.',url:outcome,kind:'ACAS GUIDANCE',force:'SHOULD',paragraph:'Telling the employee; Dismissal'},
    {id:'law-code-status',title:'Legal status of the Code',summary:'Failure to observe the statutory Code does not by itself create liability. Relevant Code provisions must be considered in employment tribunal proceedings. The Code is not an Act of Parliament, and an apparent procedural departure does not automatically invalidate a hearing or establish unlawful dismissal.',url:'https://www.legislation.gov.uk/ukpga/1992/52/section/207',kind:'OFFICIAL LAW',force:'LEGAL EFFECT',paragraph:'Trade Union and Labour Relations (Consolidation) Act 1992, section 207'},
    {id:'law-code-awards',title:'Possible tribunal award adjustment',summary:'In claims within the listed jurisdictions, where a relevant Code applies and non-compliance was unreasonable, a tribunal may adjust an award by up to 25% if just and equitable: upward for employer failure, downward for employee failure. This is not automatic compensation or a freestanding claim.',url:'https://www.legislation.gov.uk/ukpga/1992/52/section/207A',kind:'OFFICIAL LAW',force:'MAY',paragraph:'Trade Union and Labour Relations (Consolidation) Act 1992, section 207A'},
    {id:'law-service',title:'Length of service matters',summary:'As at 7 October 2026, ordinary unfair-dismissal protection generally requires two years’ continuous employment ending with the effective termination date. Exceptions exist. This tool does not assume qualifying service or eligibility; a contractual start date alone may not resolve continuity or the legally effective termination date.',url:'https://www.legislation.gov.uk/ukpga/1996/18/section/108',kind:'OFFICIAL LAW',force:'ELIGIBILITY',paragraph:'Employment Rights Act 1996, section 108'},
    {id:'law-reform',title:'Six-month reform: 1 January 2027',summary:'The reduction to six months’ qualifying service is scheduled by enacted commencement regulations for 1 January 2027. Transitional rules apply by effective termination date: before that date the reduction does not apply; on or after it the amendment applies, including where dismissal was communicated earlier. Recheck the law for the relevant date.',url:'https://www.legislation.gov.uk/uksi/2026/559/made',kind:'OFFICIAL LAW',force:'FUTURE CHANGE',paragraph:'SI 2026/559, regulations 3–4; Employment Rights Act 2025, section 25',additionalUrl:'https://www.gov.uk/government/publications/summary-of-stakeholder-roundtables-on-unfair-dismissal-changes/unfair-dismissal-changes-summary-of-stakeholder-roundtables'},
    {id:'law-reasonableness',title:'Ordinary unfair dismissal: relevant test',summary:'Where the statutory claim is available, conduct is a potentially fair reason. The employer must establish the reason; fairness also depends on whether dismissal was reasonable in the circumstances, including employer size and resources, and the merits of the case. This tool does not determine that test or a case outcome.',url:'https://www.legislation.gov.uk/ukpga/1996/18/section/98',kind:'OFFICIAL LAW',force:'LEGAL TEST',paragraph:'Employment Rights Act 1996, section 98(1), (2)(b), (4)'},
    {id:'acas-other-rights',title:'Other possible rights require facts',summary:'Some automatically unfair reasons, including qualifying whistleblowing, can give protection without two years’ service. Discrimination claims also do not require two years. Contractual claims are distinct from ordinary unfair dismissal. None of these claims is assumed to exist here; identify supporting facts and obtain advice if relevant.',url:'https://www.acas.org.uk/dismissals/unfair-dismissal',kind:'ACAS GUIDANCE',force:'ELIGIBILITY',paragraph:'Dismissal before someone has worked 2 years; Automatically unfair reasons; Discrimination'},
    {id:'acas-final-pay',title:'Summary dismissal and final pay',summary:'Gross misconduct can justify dismissal without notice. Even then, outstanding pay for work, accrued untaken holiday and owed expenses remain matters to settle. Whether a particular dismissal properly removes notice entitlement depends on the facts; do not infer it simply from an allegation.',url:'https://www.acas.org.uk/dismissals/dismissals-with-and-without-notice',kind:'ACAS GUIDANCE',force:'CONTEXT',paragraph:'Dismissal without notice for gross misconduct'},
    {id:'acas-appeal-grounds',title:'Possible grounds for appeal',summary:'An appeal can challenge severity, factual findings or procedure, and present new evidence. The employer should reconsider the case, investigate further if necessary and confirm its final decision in writing. Use the organisation’s appeal process and deadline; the Code itself sets no universal five-day deadline.',url:'https://www.acas.org.uk/appealing-a-disciplinary-or-grievance-outcome',kind:'ACAS GUIDANCE',force:'SHOULD',paragraph:'What an appeal is; The right of appeal and the law'},
    {id:'acas-time-limits',title:'Appeal and tribunal deadlines differ',summary:'Internal disciplinary, grievance and appeal processes do not change tribunal time limits. Acas states that, for most claims, problems before 1 October 2026 have a three-month-minus-one-day limit; on or after that date, six months minus one day. Exceptions and early-conciliation rules matter. Get advice promptly; this tool does not calculate a tribunal deadline.',url:'https://www.acas.org.uk/employment-tribunal-time-limits',kind:'ACAS GUIDANCE',force:'TIME LIMITS',paragraph:'Updated 1 October 2026; Grievance, disciplinary or appeal procedures',additionalUrl:'https://www.legislation.gov.uk/uksi/2026/954/made',additionalParagraph:'SI 2026/954, regulations 3–4 and Schedule: commencement and relevant-date transition',note:'Certain claims, including interim-relief applications, have much shorter limits. Do not treat the general period as applicable to every claim.'},
    {id:'acas-help',title:'Acas helpline',summary:'0300 123 1100, Monday to Friday, 8am–6pm. Acas offers confidential advice about workplace rights and options. Advice is free; your phone provider may charge for the call.',url:'https://www.acas.org.uk/contact/get-advice',kind:'ACAS GUIDANCE',force:'SUPPORT',paragraph:'Call helpline'}
  ].map(item => ({...item,verified:([code,hearing,outcome,companion,'https://www.acas.org.uk/appealing-a-disciplinary-or-grievance-outcome'].includes(item.url)?'2026-10-08':verified),status:'VERIFIED',shortQuote:''}));

  window.RW_RESPONSES = [
    {id:'working',claim:'You were still working',response:'I will explain my account; please identify the time and duties you say made this working time.',question:'Which rota, clock record, instruction or remaining duty supports that position?',source:'hours',legalSource:'acas-hearing',tags:['shift','hours','duties','service','working']},
    {id:'intoxicated',claim:'You were intoxicated',response:'Please distinguish what was observed from the conclusion that I was intoxicated.',question:'What specific behaviour, timing and evidence support impairment or being under the influence?',source:'alcohol-influence',legalSource:'acas-hearing',tags:['drunk','impaired','intoxication','alcohol']},
    {id:'staff-risk',claim:'You put staff at risk',response:'I take safety seriously and would like to understand the particular risk alleged.',question:'Who could have been affected, how, and what evidence connects my conduct to that risk?',source:'serious-safety',legalSource:'acas-hearing',tags:['staff','safety','risk','harm','potential']},
    {id:'building-risk',claim:'You put the building at risk',response:'Please identify the security responsibility and the alleged failure so I can answer it.',question:'Which lock-up, alarm, key, cash or premises-security task was allegedly affected?',source:'security',legalSource:'acas-hearing',tags:['building','security','lockup','lock-up','premises','keys']},
    {id:'manager',claim:'You are a manager',response:'I understand the importance of the role; please explain the specific managerial duty relevant to this allegation.',question:'What duty, instruction and supporting evidence are being relied upon?',source:'security',legalSource:'acas-hearing',tags:['manager','management','responsibility','leadership']},
    {id:'automatic-gm',claim:'This is automatically gross misconduct',response:'Which exact provision and established circumstances are you relying on to classify this as gross misconduct?',question:'What potential effect on performance, employees or safety do you allege, and what supports it?',source:'alcohol-gross-disciplinary',legalSource:'acas-sanctions',tags:['automatic','gross misconduct','dismissal','harm','potential effect']},
    {id:'handbook-clear',claim:'The handbook is clear',response:'Let us read the complete relevant provision and identify which facts are said to satisfy it.',question:'Which section and wording are you relying on, including any qualifications?',source:'alcohol-hours',legalSource:'acas-consistency',tags:['handbook','policy','clear','rule']},
    {id:'staff-rule',claim:'Everyone knows the Friday–Sunday staff drink rule',response:'Please identify the rule and how it was communicated so I can give an accurate response.',question:'Where is the Friday–Sunday restriction documented, and when and how was it communicated to me?',source:'staff-drink',legalSource:'acas-consistency',tags:['friday','saturday','sunday','staff drink','everyone knows','weekend','rule']},
    {id:'clocked-in',claim:'You were clocked in',response:'Please show the clock record and let us compare it with the duties and shift arrangements at that time.',question:'What duties remained, who determined shift end, and what does the record show?',source:'sign-in',legalSource:'acas-hearing',tags:['clocked','clock','timekeeping','paid','hours']},
    {id:'multiple-drinks',claim:'You had more than one drink',response:'I will give my best recollection and distinguish anything I cannot reliably remember.',question:'What quantity, drink type and times are alleged, and which evidence supports each?',source:'staff-drink',legalSource:'acas-hearing',tags:['amount','quantity','one drink','two','more','beer','wine']},
    {id:'happened-before',claim:'This has happened before',response:'Please specify each earlier incident and whether it is part of this allegation or being considered for sanction.',question:'What dates, findings and records are being relied on?',source:'investigation',legalSource:'acas-notice',tags:['before','previous','repeat','incident','history']},
    {id:'warnings',claim:'You already have warnings',response:'Please identify the warning documents, their level and current status, and explain their relevance.',question:'Are they formal, when do they expire, and how are they being used in this decision?',source:'warnings-first',legalSource:'acas-warning',tags:['warnings','lateness','prior','active','expired','final warning']},
    {id:'cctv',claim:'We have CCTV',response:'Please show the footage you rely on with its timing and surrounding context so I can respond accurately.',question:'Which footage establishes the conduct, quantity or effect alleged, and is the relevant sequence complete?',source:'acas-hearing',tags:['cctv','video','footage','camera','timestamp']},
    {id:'witness',claim:'We have a witness',response:'Please provide the witness account and the specific observations relied on so I can respond.',question:'What did the witness observe directly, at what time, and what is their interpretation?',source:'acas-notice',tags:['witness','statement','someone saw','hearsay']},
    {id:'withhold-evidence',claim:'We do not need to give you the evidence',response:'I need to understand the evidence relied on and have a reasonable opportunity to answer it.',question:'What can be provided or explained now, and what is the reason for withholding any part?',source:'acas-notice',tags:['disclosure','withheld','evidence','not give','confidential']},
    {id:'no-adjournment',claim:'We are not adjourning',response:'Please record my request, the preparation I need, and the decision and reasons for refusing it.',question:'How will I be given a reasonable opportunity to check this material and respond?',source:'acas-late-evidence',tags:['adjourn','adjournment','refused','break','preparation']},
    {id:'decided',claim:'We have already made our decision',response:'Please clarify whether the outcome remains open to my evidence, explanation and mitigation.',question:'Will my response be considered before a final decision is reached?',source:'acas-deliberation',tags:['decided','decision','predetermined','already','outcome']},
    {id:'why-not-dismiss',claim:'Why should we not dismiss you?',response:'I would like you to consider my account, the evidence and the mitigation I can substantiate before choosing a sanction.',question:'Which lesser outcomes have been considered, and how have the relevant circumstances been weighed?',source:'sanctions',legalSource:'acas-proportionality',tags:['dismiss','dismissal','sack','mitigation','proportionality']},
    {id:'accept-gm',claim:'Do you accept gross misconduct?',response:'I will be clear about the conduct I accept or dispute; please explain how you say the established facts meet gross misconduct.',question:'Which provision and facts support that classification?',source:'alcohol-gross-disciplinary',legalSource:'acas-sanctions',tags:['admit','accept','gross misconduct','guilty','classification']},
    {id:'resign',claim:'Do you want to resign?',response:'I would like time to consider that question and take advice before making a decision about my employment.',question:'Are you proposing resignation as an option, or communicating a disciplinary decision?',source:'acas-help',tags:['resign','resignation','leave','pressure']},
    {id:'late-evidence',claim:'Here is new evidence',response:'I would like reasonable time to review this new material before giving a complete response.',question:'May we pause while I review it, and confirm when and how I can respond?',source:'acas-late-evidence',tags:['new','late','evidence','surprise','adjournment']},
    {id:'new-allegation',claim:'There is another allegation',response:'Please set out the additional allegation, supporting evidence and possible consequences before I respond fully.',question:'What preparation time will be provided for this additional issue?',source:'acas-notice',tags:['new allegation','additional','another','change','scope']},
    {id:'companion-refused',claim:'You cannot bring that companion',response:'I am requesting an eligible companion and would like the reason for refusal explained and recorded.',question:'Is eligibility disputed, or is the issue availability or a proposed reasonable adjustment?',source:'law-companion',tags:['companion','union','colleague','representation','refused']},
    {id:'companion-unavailable',claim:'The hearing goes ahead without your companion',response:'If my chosen eligible companion is unavailable, I would like to propose a reasonable alternative within the statutory period.',question:'Will you consider my proposed time within five working days after the original date?',source:'law-postponement',tags:['companion','postpone','unavailable','five days','attendance']},
    {id:'companion-silent',claim:'Your companion cannot speak',response:'Please allow my companion to present and sum up my case, respond to views and confer with me.',question:'Which part of the companion’s proposed contribution is being restricted, and why?',source:'law-companion-role',tags:['companion','speak','silent','union','role']},
    {id:'authorised',claim:'Nobody authorised your drink',response:'Let us establish who had authority and what was said or done before the drink.',question:'What evidence of authorisation or its absence has been considered?',source:'staff-drink',legalSource:'acas-investigation',tags:['authorised','permission','duty manager','allowed','staff drink']},
    {id:'no-harm',claim:'There does not have to be actual harm',response:'I understand potential effects may matter; please identify the particular effect or risk alleged in these circumstances.',question:'What evidence supports that possible effect or risk?',source:'alcohol-gross',legalSource:'acas-sanctions',tags:['actual harm','potential','risk','impact','no incident']},
    {id:'appeal',claim:'This is the final outcome',response:'Please provide the written reasons, evidence relied on, sanction and appeal instructions.',question:'Who receives an appeal, by what deadline, and who will hear it?',source:'appeal',legalSource:'acas-appeal',tags:['appeal','final','outcome','dismissed','deadline']},
    {id:'short-service',claim:'You have not worked here long enough',response:'I understand service can affect particular claims; I would still like the stated procedure and my response to be considered.',question:'Which decision or procedural right do you say is affected by my length of service?',source:'law-service',legalSource:'law-companion',tags:['service','probation','two years','six months','rights','new employee']},
    {id:'notes-wrong',claim:'These are the agreed meeting notes',response:'Please let me review them and identify any corrections or points that remain disputed.',question:'Can my corrections be attached to the record if we do not agree the wording?',source:'acas-hearing',tags:['notes','minutes','record','agreed','correction']}
  ];
})();
